server:
  port: 7002 # 端口号
eureka:
  instance:
    hostname: eurekaserver02.com # 服务地址
  client:
    register-with-eureka: false #是否向注册中心注册
    fetch-registry: false # 是否去用户中心获取其他已注册服务信息
    service-url:
      defaultZone: http://eurekaserver01.com:7001/eureka/,http://eurekaserver03.com:7003/eureka/
