server:
  port: 8002

spring:
   application:
      name: micro-client:8002
eureka:
  client:
    fetch-registry: true # 是否去注册中心获取其他注册模块信息
    service-url:
      defaultZone: http://eurekaserver01.com:7001/eureka,http://eurekaserver02.com:7002/eureka,http://eurekaserver03.com:7003/eureka  # 注册中心地址
  instance:
    instance-id: micro-client:8002 # 本服务实例信息
    prefer-ip-address: true