server:
  port: 7001 # 端口号
eureka:
  instance:
    hostname: localhost # 服务地址
  client:
    register-with-eureka: false #是否向注册中心注册
    fetch-registry: false # 是否去用户中心获取其他已注册服务信息
#    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/
#    service-url:
#      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
