server:
  port: 8003

spring:
  zipkin:
    base-url: http://yuluocloud.com:9411/
    sleuth:
      sampler:
        percentage: 1.0
  application:
    name: micro-consumer
eureka:
  client:
    fetch-registry: true # 是否去注册中心获取其他注册模块信息
    service-url:
      defaultZone: http://eurekaserver01.com:7000/eureka #,http://eurekaserver02.com:7002/eureka,http://eurekaserver03.com:7003/eureka  # 注册中心地址
  instance:
    instance-id: micro-consumer:8003 # 本服务实例信息
    prefer-ip-address: true