server:
  port: 9002
spring:
  application:
    name: consul-consumer
  cloud:
    consul: # consul服务配置
      host: localhost
      port: 8500 # consul服务端口号
      discovery:
        register: true #是否需要注册
        instance-id: ${spring.application.name} # 注册实例ID
        service-name: ${spring.application.name} # 服务名称
        port: ${server.port} # 服务请求端口号
        prefer-ip-adress: true # 指定开启IP地址注册
        ip-adress: ${spring.cloud.client.ip-adress} # 当前服务的ip地址